[package]
name = "k4q"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
home = '0.5.3'
indicatif = "0.17.0-beta.1"
predicates = "2.0.0"
rdkafka = { version = "0.25", features = ["cmake-build"] }
serde = "1.0"
serde_json = "1.0"
shaku = "0.6.1"
futures = "0.3"