[package]
name = "k4fq"
version = "0.1.0"
edition = "2021"
rust-version = "1.72.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.1.5"
home = '0.5.4'
indicatif = "0.17.3"
predicates = "3.0.3"
rdkafka = { version = "0.34.0", features = ["cmake-build"] }
serde = "1.0"
serde_json = "1.0"
erased-serde = "0.3"
config = "0.13"
rayon = '1.6'
crossbeam = '0.8'
tokio = { version = "1", features = ["full"] }
do-notation = "0.1"
itertools = "0.11.0"

[dev-dependencies]
# latest version - 0.12.0 doesn't contain kafka, so I used latest dev instead
#testcontainers = { git="https://github.com/testcontainers/testcontainers-rs.git", ref="4b6b59f8fccd51cca812662df1701a3186a87b1f" }
testcontainers = "0.14"

log = "0.4"
log4rs = "1"
assert_cmd = "2.0"

mockall = "0.11"

futures = '0.3'
