[package]
name = "kaf"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
predicates = "2.0.0"
rdkafka = { version = "0.25", features = ["cmake-build"] }
shaku = "0.6.1"
home = '0.5.3'
