[package]
name = "k4q"
version = "0.1.0"
edition = "2021"
rust-version = "1.56.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
home = '0.5.3'
indicatif = "0.17.0-beta.1"
predicates = "2.0.0"
rdkafka = { version = "0.25", features = ["cmake-build"] }
serde = "1.0"
serde_json = "1.0"
erased-serde = "0.3"
shaku = "0.6.1"
futures = "0.3"
config = "0.11"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
# latest version - 0.12.0 doesn't contain kafka, so I used latest dev instead
testcontainers = { git="https://github.com/testcontainers/testcontainers-rs.git", ref="4b6b59f8fccd51cca812662df1701a3186a87b1f" }

log = "0.4"
log4rs = "1"
assert_cmd = "2.0"
